version: "3.7"
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        image: appsdaroi
        container_name: appsdaroi
        restart: unless-stopped
        ports:
            - 8290:80
        volumes:
            - ./:/app/
    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: unless-stopped
        tty: true
        ports:
            - 8291:3306
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
            MYSQL_ROOT_PASSWORD: laravel
        volumes:
            - mysql-data:/var/lib/mysql
            - ./mysql/my.cnf:/etc/mysql/my.cnf
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        container_name: phpmyadmin
        restart: unless-stopped
        ports:
            - 8292:80
        environment:
            PMA_HOST: mysql
            MYSQL_ROOT_PASSWORD: laravel
        depends_on:
            - mysql

volumes:
    mysql-data:
